class Autogenerated {
  List<Items>? items;

  Autogenerated({this.items});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['items'] != null) {
      items = <Items>[];
      json['items'].forEach((v) {
        items!.add( Items.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data =  <String, dynamic>{};
    if (items != null) {
      data['items'] = items!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Items {
  String? formName;
  String? lablename;
  int? maxlengeth;
  String? title;
  List<Data>? data;

  Items(
      {this.formName, this.lablename, this.maxlengeth, this.title, this.data});

  Items.fromJson(Map<String, dynamic> json) {
    formName = json['FormName'];
    lablename = json['Lablename'];
    maxlengeth = json['maxlengeth'];
    title = json['title'];
    if (json['data'] != null) {
      data = <Data>[];
      json['data'].forEach((v) {
        data!.add(Data.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['FormName'] = formName;
    data['Lablename'] = lablename;
    data['maxlengeth'] = maxlengeth;
    data['title'] = title;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Data {
  String? data1;
  String? data2;
  String? data3;

  Data({this.data1, this.data2, this.data3});

  Data.fromJson(Map<String, dynamic> json) {
    data1 = json['data1'];
    data2 = json['data2'];
    data3 = json['data3'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['data1'] = data1;
    data['data2'] = data2;
    data['data3'] = data3;
    return data;
  }
}