import 'dart:convert';

import 'package:dio/dio.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

import 'package:sample/model/user.dart';
import 'dart:convert';

class Sample extends StatefulWidget {
  Sample({Key? key}) : super(key: key);

  @override
  State<Sample> createState() => _SampleState();
}


 Map<String, dynamic> userMap = jsonDecode("");
var user = Autogenerated.fromJson(userMap);

class _SampleState extends State<Sample> {
 
  bool apiCall = false;

  String message = '';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              message,
              style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 18.0),
            ),
            RaisedButton(
              child: const Text(
                "Click",
                style: TextStyle(fontWeight: FontWeight.bold, fontSize: 18.0),
              ),
              onPressed: () async {
                apiCall = true; // Set state like this
                Autogenerated? fMain = await getUser();
               // message = fMain!.name!;
                setState(() {});
                print('$fMain ');
              },
            ),
          ],
        ),
      ),
    );
  }
   Future<Autogenerated?> getUser() async {
    try {
      const String _endpoint =
          "http://echo.jsontest.com/key/value/message/testmessage";
      Dio dio =  Dio();
      var response = await dio
          .get(_endpoint);
      print("user API response - : $response ");
      setState(() {
        apiCall = false;
      });
    
      return Autogenerated.fromJson(response.data);
    } catch (error, stacktrace) {
      print("Exception occured: $error stackTrace: $stacktrace");
      //return MemberLogin.withError("$error");
    }
  }
}
